"""RoboTwin20 EnvironmentAdapter with a sensor-only, provider-neutral seam."""

from importlib import import_module
from typing import Any

from .action_readiness import (
    ACTION_READINESS_PROFILE_SCHEMA_VERSION,
    ActionReadinessConfigurationError,
    ReadinessEvidenceGate,
    build_action_readiness_gate,
    build_complete_route_readiness_gate,
    load_action_readiness_profile,
)
from .adapter import (
    AdapterConfigurationError,
    AdapterSensorError,
    RoboTwin20Adapter,
    RoboTwinObservationSource,
    RoboTwinSensorBackend,
    SensorArtifact,
    SensorCapture,
)
from .grasp_adaptation import (
    GRASP_ADAPTATION_PROFILE_SCHEMA_VERSION,
    GraspAdaptationError,
    adapt_grasp_candidate,
    camera_pose_to_world_matrix,
)
from .grasp_profile import (
    GRASP_PROFILE_SCHEMA_VERSION,
    GraspProfileError,
    build_grasp_provider,
    load_grasp_profile,
)
from .grasp_proposal import (
    FilesystemPointCloudArtifactResolver,
    GraspGenProposalProvider,
    GraspProposalAdapterError,
    GraspWorkerClient,
    PointCloudArtifactResolver,
)
from .openai_scene_understanding import (
    SCENE_UNDERSTANDING_JSON_SCHEMA,
    ArtifactPayload,
    ArtifactResolver,
    FilesystemArtifactResolver,
    OpenAIResponsesConfig,
    OpenAIResponsesInferenceError,
    OpenAIResponsesSceneUnderstandingInference,
)
from .perception_profile import (
    PROFILE_SCHEMA_VERSION,
    PerceptionProfileError,
    build_single_view_perception,
    load_perception_profile,
)
from .process_worker import JsonlProcessWorkerClient, ProcessWorkerConfig, ProcessWorkerError
from .readiness import ReadinessAdapterError, ReadinessEvaluator, RoboTwinReadinessEvaluator
from .readiness_profile import (
    LIVE_READINESS_PROFILE_SCHEMA_VERSION,
    READINESS_PROFILE_SCHEMA_VERSION,
    ReadinessLiveClient,
    ReadinessProfileError,
    ReadinessReplayClient,
    build_live_readiness_evaluator,
    build_readiness_evaluator,
    load_readiness_profile,
)
from .readiness_replay import (
    READINESS_REPLAY_ARTIFACT_SCHEMA_VERSION,
    ReadinessReplayArtifactError,
    load_readiness_replay_artifact,
    readiness_replay_artifact_id,
    validate_readiness_replay_artifact,
    write_readiness_replay_artifact,
)
from .route_evidence import (
    ROUTE_EVIDENCE_PROFILE_SCHEMA_VERSION,
    ROUTE_EVIDENCE_SCHEMA_VERSION,
    RouteEvidenceClient,
    RouteEvidenceError,
    build_route_evidence_client,
    load_route_evidence_profile,
    verify_route_evidence,
)
from .route_generation import (
    RouteGenerationError,
    generate_route_request,
    validate_route_policy,
)
from .route_inputs import (
    OBJECT_GEOMETRY_SCHEMA_VERSION,
    OBJECT_ROBOT_TARGET_TRANSFORM_SCHEMA_VERSION,
    PLACEMENT_TARGET_SCHEMA_VERSION,
    ROUTE_INPUT_PROFILE_SCHEMA_VERSION,
    ROUTE_SCENE_FACTS_SCHEMA_VERSION,
    RouteInputError,
    canonical_json,
    derive_bound_route_inputs,
    sha256_json,
    validate_scene_facts,
)
from .route_readiness import (
    ROUTE_CHECKS,
    ROUTE_PHASES,
    ROUTE_READINESS_PROFILE_SCHEMA_VERSION,
    ROUTE_REQUEST_SCHEMA_VERSION,
    SIMULATION_ROUTE_READINESS_SCHEMA_VERSION,
    RouteReadinessClient,
    RouteReadinessError,
    RouteReadinessEvaluationAdapter,
    RouteReadinessProfileError,
    build_route_readiness_client,
    load_route_readiness_profile,
    project_route_evidence,
    route_geometry_digest,
    validate_route_request,
)
from .simulation_authorization import (
    SIMULATION_APPROVAL_SCHEMA_VERSION,
    SIMULATION_AUTHORIZATION_PROFILE_SCHEMA_VERSION,
    SIMULATION_EVIDENCE_MANIFEST_SCHEMA_VERSION,
    SimulationAuthorizationError,
    SimulationMotionAuthorizationProfile,
    load_simulation_motion_profile,
)
from .simulation_probe import (
    SIMULATION_PROBE_PROFILE_SCHEMA_VERSION,
    SIMULATION_PROBE_RESPONSE_SCHEMA_VERSION,
    SimulationProbeClient,
    SimulationProbeProfileError,
    build_simulation_probe_client,
    load_simulation_probe_profile,
)
from .single_view_perception import (
    FilesystemPerceptionArtifactStore,
    LocalizationRequest,
    LocalizationResult,
    MetricLocalizationProvider,
    NumpyMetricLocalizationProvider,
    Proposal,
    ProposalProvider,
    ProposalRequest,
    SegmentationProvider,
    SegmentationRequest,
    SegmentationResult,
    SingleViewPerceptionError,
    SingleViewPerceptionInference,
    WorkerClient,
    WorkerProposalProvider,
    WorkerSegmentationProvider,
)
from .understanding import (
    RoboTwinSceneUnderstandingProvider,
    RoboTwinUnderstandingSnapshot,
    SceneUnderstandingInference,
)

_LAZY_ARM_CANDIDATE_EXPORTS = {
    "ARM_PLANNING_PROFILE_SCHEMA_VERSION",
    "ROUTE_EVALUATION_SCHEMA_VERSION",
    "ROUTE_SELECTION_SCHEMA_VERSION",
    "ArmPlanningError",
    "build_capability_snapshot",
    "CompleteRouteSelector",
    "enumerate_arm_candidates",
    "load_arm_planning_profile",
    "project_arm_assignment",
    "validate_arm_planning_profile",
}


def __getattr__(name: str) -> Any:
    """Load PAOS-coupled planning exports only when callers request them."""
    if name not in _LAZY_ARM_CANDIDATE_EXPORTS:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    value = getattr(import_module(f"{__name__}.arm_candidates"), name)
    globals()[name] = value
    return value

__all__ = [
    "ARM_PLANNING_PROFILE_SCHEMA_VERSION",
    "ROUTE_EVALUATION_SCHEMA_VERSION",
    "ROUTE_SELECTION_SCHEMA_VERSION",
    "ArmPlanningError",
    "CompleteRouteSelector",
    "enumerate_arm_candidates",
    "load_arm_planning_profile",
    "validate_arm_planning_profile",
    "AdapterConfigurationError",
    "AdapterSensorError",
    "RoboTwin20Adapter",
    "RoboTwinObservationSource",
    "RoboTwinSensorBackend",
    "SensorArtifact",
    "SensorCapture",
    "ActionReadinessConfigurationError",
    "ACTION_READINESS_PROFILE_SCHEMA_VERSION",
    "ReadinessEvidenceGate",
    "build_action_readiness_gate",
    "build_complete_route_readiness_gate",
    "load_action_readiness_profile",
    "RoboTwinSceneUnderstandingProvider",
    "RoboTwinUnderstandingSnapshot",
    "SceneUnderstandingInference",
    "ArtifactPayload",
    "ArtifactResolver",
    "FilesystemArtifactResolver",
    "OpenAIResponsesConfig",
    "OpenAIResponsesInferenceError",
    "OpenAIResponsesSceneUnderstandingInference",
    "SCENE_UNDERSTANDING_JSON_SCHEMA",
    "PROFILE_SCHEMA_VERSION",
    "PerceptionProfileError",
    "build_single_view_perception",
    "load_perception_profile",
    "JsonlProcessWorkerClient",
    "ProcessWorkerConfig",
    "ProcessWorkerError",
    "GraspGenProposalProvider",
    "GraspProposalAdapterError",
    "GraspWorkerClient",
    "FilesystemPointCloudArtifactResolver",
    "PointCloudArtifactResolver",
    "GRASP_PROFILE_SCHEMA_VERSION",
    "GRASP_ADAPTATION_PROFILE_SCHEMA_VERSION",
    "GraspAdaptationError",
    "adapt_grasp_candidate",
    "camera_pose_to_world_matrix",
    "GraspProfileError",
    "build_grasp_provider",
    "load_grasp_profile",
    "FilesystemPerceptionArtifactStore",
    "LocalizationRequest",
    "LocalizationResult",
    "MetricLocalizationProvider",
    "NumpyMetricLocalizationProvider",
    "Proposal",
    "ProposalProvider",
    "ProposalRequest",
    "SegmentationProvider",
    "SegmentationRequest",
    "SegmentationResult",
    "SingleViewPerceptionError",
    "SingleViewPerceptionInference",
    "WorkerClient",
    "WorkerProposalProvider",
    "WorkerSegmentationProvider",
    "ReadinessAdapterError",
    "ReadinessEvaluator",
    "RoboTwinReadinessEvaluator",
    "READINESS_PROFILE_SCHEMA_VERSION",
    "LIVE_READINESS_PROFILE_SCHEMA_VERSION",
    "ReadinessProfileError",
    "ReadinessLiveClient",
    "ReadinessReplayClient",
    "build_live_readiness_evaluator",
    "build_readiness_evaluator",
    "load_readiness_profile",
    "READINESS_REPLAY_ARTIFACT_SCHEMA_VERSION",
    "ReadinessReplayArtifactError",
    "load_readiness_replay_artifact",
    "readiness_replay_artifact_id",
    "validate_readiness_replay_artifact",
    "write_readiness_replay_artifact",
    "ROUTE_CHECKS",
    "ROUTE_PHASES",
    "ROUTE_READINESS_PROFILE_SCHEMA_VERSION",
    "ROUTE_REQUEST_SCHEMA_VERSION",
    "SIMULATION_ROUTE_READINESS_SCHEMA_VERSION",
    "RouteReadinessClient",
    "RouteReadinessError",
    "RouteReadinessEvaluationAdapter",
    "RouteReadinessProfileError",
    "build_route_readiness_client",
    "load_route_readiness_profile",
    "project_route_evidence",
    "route_geometry_digest",
    "validate_route_request",
    "RouteGenerationError",
    "generate_route_request",
    "OBJECT_GEOMETRY_SCHEMA_VERSION",
    "OBJECT_ROBOT_TARGET_TRANSFORM_SCHEMA_VERSION",
    "PLACEMENT_TARGET_SCHEMA_VERSION",
    "ROUTE_INPUT_PROFILE_SCHEMA_VERSION",
    "ROUTE_SCENE_FACTS_SCHEMA_VERSION",
    "RouteInputError",
    "canonical_json",
    "derive_bound_route_inputs",
    "sha256_json",
    "validate_scene_facts",
    "validate_route_policy",
    "ROUTE_EVIDENCE_PROFILE_SCHEMA_VERSION",
    "ROUTE_EVIDENCE_SCHEMA_VERSION",
    "RouteEvidenceClient",
    "RouteEvidenceError",
    "build_route_evidence_client",
    "load_route_evidence_profile",
    "verify_route_evidence",
    "SIMULATION_AUTHORIZATION_PROFILE_SCHEMA_VERSION",
    "SIMULATION_APPROVAL_SCHEMA_VERSION",
    "SIMULATION_EVIDENCE_MANIFEST_SCHEMA_VERSION",
    "SimulationAuthorizationError",
    "SimulationMotionAuthorizationProfile",
    "load_simulation_motion_profile",
    "SIMULATION_PROBE_PROFILE_SCHEMA_VERSION",
    "SIMULATION_PROBE_RESPONSE_SCHEMA_VERSION",
    "SimulationProbeClient",
    "SimulationProbeProfileError",
    "build_simulation_probe_client",
    "load_simulation_probe_profile",
]
